server:
  address: 0.0.0.0
 
spring:
  resources:
    static-locations: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://211.149.174.104:3306/chat?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: dy!@#741852963
    continue-on-error: false
    name: MYSQL
    platform: all
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 16
      auto-commit: true
      idle-timeout: 3000
      max-lifetime: 60000
      connection-timeout: 30000
    tomcat:
      max-active: 200
      initial-size: 5
      max-wait: 30000
      min-idle: 5
      max-idle: 5
      validation-query: SELECT 1
      validation-query-timeout: 30000
      validation-interval: 30000
      test-on-connect: true
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      time-between-eviction-runs-millis: 30000
      max-age: 14400000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        
  jmx:
    enabled: false
  mail:
    host: smtp.126.com
    port: 465
    username: ewdaoyuan@126.com
    password: ewdy123456
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      